# source: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume-nfs
  labels:
    type: storage-nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-storage-nfs
  nfs:
    path: /home/tzahi/nfsshare/storage/postgres-clalit
    server: 172.22.54.171
    readOnly: false
