---
#  Source: https://artifacthub.io/packages/helm/argo/argo-cd

#   What is a helmfile? Read here... https://github.com/helmfile/helmfile
#   Examples: https://github.com/helmfile/helmfile/blob/main/examples/charts/argocd-helmfile-deployment/helmfile.yaml

# Before deployment, export the required env vars
# export HELM_SECRETS_DRIVER=vault

# Commands to deploy:
# helmfile deps  # < download dependencies
# helmfile template  # < template stuff. You might have to be signed into vault
# helmfile sync  # < deploy everything
# helmfile apply  # < deploy diff only
# helmfile destroy  # < deploy diff only
filepath: helmfile.yaml
helmBinary: helm
# kustomizeBinary: kustomize
helmDefaults:
  # verify: false
  # enableDNS: false
  # waitForJobs: false
  timeout: 60
  # skipDeps: false
  # reuseValues: false
  # deleteWait: false
  # deleteTimeout: 0
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
releases:
  - name: argo-cd
    installed: true
    namespace: '{{`{{ .Release.Name }}`}}'
    createNamespace: true
    chart: argo/{{`{{ .Release.Name }}`}}
    labels:
      app.kubernetes.io/name: argocd
  #   version: 7.0.0
  #   missingFileHandler: Warn  # set to either "Error" or "Warn". "Error" instructs helmfile to fail when unable to find a values or secrets file. When "Warn", it prints the file and continues.
  #   verify: true
    cleanupOnFail: true
    values:
      - charts/{{`{{ .Release.Name }}`}}/values.yaml
      - charts/{{`{{ .Release.Name }}`}}/values-{{`{{ .Release.Name }}`}}.yaml
  - name: argocd-apps
    installed: false
    namespace: argo-cd
    createNamespace: true
    chart: argo/{{`{{ .Release.Name }}`}}
    labels:
      app.kubernetes.io/name: '{{`{{ .Release.Name }}`}}'
  #   version: 2.0.0
  #   missingFileHandler: Warn  # set to either "Error" or "Warn". "Error" instructs helmfile to fail when unable to find a values or secrets file. When "Warn", it prints the file and continues.
  #   verify: true
    cleanupOnFail: true
    values:
      # - "charts/{{`{{ .Release.Name }}`}}/values.yaml"
      - charts/{{`{{ .Release.Name }}`}}/values-{{`{{ .Release.Name }}`}}.yaml
  - name: argocd-image-updater
    installed: false
    namespace: argo-cd
    createNamespace: true
    chart: argo/{{`{{ .Release.Name }}`}}
    labels:
      app.kubernetes.io/name: '{{`{{ .Release.Name }}`}}'
  #   version: 0.10.1
  #   missingFileHandler: Warn  # set to either "Error" or "Warn". "Error" instructs helmfile to fail when unable to find a values or secrets file. When "Warn", it prints the file and continues.
  #   verify: true
    cleanupOnFail: true
    values:
      # - "charts/{{`{{ .Release.Name }}`}}/values.yaml"
      - charts/{{`{{ .Release.Name }}`}}/values-{{`{{ .Release.Name }}`}}.yaml
  - name: argo-events
    installed: false
    namespace: argo-cd
    createNamespace: true
    chart: argo/{{`{{ .Release.Name }}`}}
    labels:
      app.kubernetes.io/name: '{{`{{ .Release.Name }}`}}'
  #   version: 2.4.5
  #   missingFileHandler: Warn  # set to either "Error" or "Warn". "Error" instructs helmfile to fail when unable to find a values or secrets file. When "Warn", it prints the file and continues.
  #   verify: true
    cleanupOnFail: true
    values:
      # - "charts/{{`{{ .Release.Name }}`}}/values.yaml"
      - charts/{{`{{ .Release.Name }}`}}/values-{{`{{ .Release.Name }}`}}.yaml
  - name: argo-rollouts
    installed: true
    namespace: argo-cd
    createNamespace: true
    chart: argo/{{`{{ .Release.Name }}`}}
    labels:
      app.kubernetes.io/name: '{{`{{ .Release.Name }}`}}'
  #   version: 2.35.3
  #   missingFileHandler: Warn  # set to either "Error" or "Warn". "Error" instructs helmfile to fail when unable to find a values or secrets file. When "Warn", it prints the file and continues.
  #   verify: true
    cleanupOnFail: true
    values:
      # - "charts/{{`{{ .Release.Name }}`}}/values.yaml"
      - charts/{{`{{ .Release.Name }}`}}/values-{{`{{ .Release.Name }}`}}.yaml
  - name: argo-workflows
    installed: false
    namespace: argo-cd
    # createNamespace: true
    chart: argo/{{`{{ .Release.Name }}`}}
    labels:
      app.kubernetes.io/name: '{{`{{ .Release.Name }}`}}'
  #   version: 0.41.7
  #   missingFileHandler: Warn  # set to either "Error" or "Warn". "Error" instructs helmfile to fail when unable to find a values or secrets file. When "Warn", it prints the file and continues.
  #   verify: true
    cleanupOnFail: true
    values:
      # - "charts/{{`{{ .Release.Name }}`}}/values.yaml"
      # - "service/argocd-service.yaml"
      - charts/{{`{{ .Release.Name }}`}}/values-{{`{{ .Release.Name }}`}}.yaml
