---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  default.conf: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Employee List</title>
    </head>
    <body>
        <h1>Employee List</h1>
        <table border="1">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Position</th>
            </tr>
            {% for employee in employees %}
            <tr>
                <td>{{ employee['id'] }}</td>
                <td>{{ employee['name'] }}</td>
                <td>{{ employee['position'] }}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
    </html>
