{
 "title": "Jira General",
 "tags": [ "jira" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "com_atlassian_jira_issue_assigned_count_Value"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "com_atlassian_jira_issue_assigned_count_Value"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Recent Alerts",
   "type": "alertlist",
   "gridPos": { "h": 11, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=\"$namespace\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{gc}} - {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{namespace=\"$namespace\", service=\"$service\"} * 1000)",
     "legendFormat": "cpu load - {{ pod }}"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", area=\"heap\"}/jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\", area=\"heap\"})",
     "legendFormat": "Used {{ area }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{gc}} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{namespace=\"$namespace\", service=\"$service\", state=\"BLOCKED\"}",
     "legendFormat": "{{ pod }} {{ state }}"
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( Catalina_ThreadPool_currentThreadCount{namespace=\"$namespace\", service=\"$service\"} / Catalina_ThreadPool_maxThreads{namespace=\"$namespace\", service=\"$service\"}) * 100",
     "legendFormat": "used - {{ pod }} ({{name}})"
    }
   ]
  },
  {
   "title": "Tomcat Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_requestCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} count - {{ pod }}"
    }
   ]
  },
  {
   "title": "Tomcat Error Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_errorCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} error - {{ pod }}"
    }
   ]
  },
  {
   "title": "Tomcat Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_processingTime{namespace=\"$namespace\", service=\"$service\"}[10m]) / increase(Catalina_GlobalRequestProcessor_requestCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "{{name}} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Tomcat Sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Catalina_Manager_activeSessions{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "active sessions: {{ pod }}"
    },
    {
     "expr": "Catalina_Manager_rejectedSessions{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "rejected sessions: {{ pod }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Connection Pool Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(com_atlassian_jira_BasicDataSource_NumActive{namespace=\"$namespace\", service=\"$service\", connectionpool=\"connections\"} / com_atlassian_jira_BasicDataSource_MaxTotal{namespace=\"$namespace\", service=\"$service\", connectionpool=\"connections\"}) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_BasicDataSource_NumActive{namespace=\"$namespace\", service=\"$service\", connectionpool=\"connections\"}",
     "legendFormat": "active - {{ pod }}"
    },
    {
     "expr": "com_atlassian_jira_BasicDataSource_NumIdle{namespace=\"$namespace\", service=\"$service\", connectionpool=\"connections\"}",
     "legendFormat": "idle - {{ pod }}"
    }
   ]
  },
  {
   "title": "Reads / Writes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(com_atlassian_jira_db_reads_invocation_count{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "reads - {{ pod }}"
    },
    {
     "expr": "delta(com_atlassian_jira_db_writes_invocation_count{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "writes - {{ pod }}"
    }
   ]
  },
  {
   "title": "Database Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"connection\", category02=\"latency\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}