---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-environment-variables
  # namespace: job-project
data:
  HOST_VAR: 'postgresql.postgresql.svc.cluster.local'
  PORT_DB_VAR: '5432'
  PORT_VAR: '5000'
  DB_VAR: 'flaskappdb'
  USER_VAR: 'flaskappuser'
  PASSWORD_VAR: '12345'
