---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-environment-variables
data:
  HOST_VAR: 'postgresql-db-hl.tzahicohen.svc.cluster.local'
  PORT_DB_VAR: '5432'
  PORT_VAR: '5000'
  DB_VAR: 'employees'
  USER_VAR: 'postgres'
  PASSWORD_VAR: 'mydbpassword'
