---
replicaCount: 1

image:
  repository: mjhfvi/clalit-python-env
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

configMap:
  enabled: true
  data:
    MY_ENV_VAR: "some value"
    ANOTHER_ENV_VAR: "another value"
    HOST_VAR: 'postgresql-db-hl.tzahicohen.svc.cluster.local'
    PORT_DB_VAR: '5432'
    PORT_VAR: '5000'
    DB_VAR: 'employees'
    USER_VAR: 'postgres'
    PASSWORD_VAR: 'mydbpassword'

resources: {}
