apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python.fullname" . }}
  labels:
    app: {{ include "python.name" . }}
    chart: {{ include "python.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "python.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "python.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: {{ include "python.fullname" . }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              subPath: config.yaml
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 5000
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 5000
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "python.fullname" . }}
            items:
              - key: MY_ENV_VAR
                path: config.yaml
